updates: 
  - commit-message: 
      include: scope
      prefix: chore
    directory: /
    labels: 
      - dependencies
    open-pull-requests-limit: 99
    package-ecosystem: npm
    #reviewers: # NOTE: Edit this to your github username and then uncomment
    #  - Hazmi35
    schedule: 
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
  - commit-message: 
      include: scope
      prefix: ci
    directory: /
    labels: 
      - gh-actions
      - dependencies
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    #reviewers: # NOTE: Edit this to your github username and then uncomment
    #  - Hazmi35
    schedule: 
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
version: 2